Repository tigergraph/server-docs, pull requests merged in 2024-10, with the labels that each got.

#554 Fix typo in point-in-time-restore.adoc (4.1)
  modules/backup-and-restore/pages/point-in-time-restore.adoc
Labels: bug

#561 DOC-2347 Docker: Add note on using different container and volume names (all ver)
  modules/getting-started/pages/docker.adoc
Labels: doc improv

#552 DOC-2346 Fix cdc-setup typo (3.10 - 4.1)
  modules/system-management/pages/change-data-capture/cdc-setup.adoc
Labels: bug

#530 DOC-2301 docs(backup): add s3 backup roleARN config (3.11)
  modules/backup-and-restore/pages/configurations.adoc
  modules/reference/pages/configuration-parameters.adoc
Labels: enhancement

#539 DOC-2272 feat(ha-overview): Backup HA (3.11)
  modules/cluster-and-ha-management/pages/ha-overview.adoc
Labels: enhancement

#532 DOC-2271 doc(cdc): change CDC message MAP attribute formati; DOC-2031 doc(cdc): add graph field to CDC message [3.11]
  modules/system-management/pages/change-data-capture/cdc-message-example.adoc
Labels: enhancement

#540 DOC-2269 docs(backup): add --custom-tag for BACKUP (3.11)
  modules/backup-and-restore/pages/backup-cluster.adoc
Labels: enhancement

#541 doc-2285 feat(configuration-parameters.backup): support Azure blob (3.11, 4.1.1, 4.2)
  modules/backup-and-restore/pages/configurations.adoc
  modules/reference/pages/configuration-parameters.adoc
Labels: enhancement

#525 DOC-2343 Add missing privileges to Built-in Roles table (3.10)
  modules/user-access/pages/access-control-model.adoc
Labels: enhancement

#497 DOC-2261 docs(crr): fix Enable the CRR setup (3.10 - 4.1)
  modules/cluster-and-ha-management/pages/set-up-crr.adoc
Labels: bug

#550 DOC-2062 Note changes to the exported contents for EXPORT (4.1)
  modules/backup-and-restore/pages/database-import-export.adoc
  modules/backup-and-restore/pages/single-graph-import-export.adoc
Labels: bug, enhancement
